// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5jh_Us5KEevmw72mRIwn5QR-ZOVUuza8',
    appId: '1:1093757867591:web:cd85eec07bd6dd14838362',
    messagingSenderId: '1093757867591',
    projectId: 'todotask-fdef8',
    authDomain: 'todotask-fdef8.firebaseapp.com',
    storageBucket: 'todotask-fdef8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GV3EvU5aL9xt58Tw_miIyU4ktVHS3UY',
    appId: '1:1093757867591:android:710ffc6fc05cb83d838362',
    messagingSenderId: '1093757867591',
    projectId: 'todotask-fdef8',
    storageBucket: 'todotask-fdef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqH6BrwQAOqJsqwIowa5fE0XpzJV4dCdc',
    appId: '1:1093757867591:ios:44db067d788e07ed838362',
    messagingSenderId: '1093757867591',
    projectId: 'todotask-fdef8',
    storageBucket: 'todotask-fdef8.appspot.com',
    iosBundleId: 'com.example.todoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqH6BrwQAOqJsqwIowa5fE0XpzJV4dCdc',
    appId: '1:1093757867591:ios:44db067d788e07ed838362',
    messagingSenderId: '1093757867591',
    projectId: 'todotask-fdef8',
    storageBucket: 'todotask-fdef8.appspot.com',
    iosBundleId: 'com.example.todoTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5jh_Us5KEevmw72mRIwn5QR-ZOVUuza8',
    appId: '1:1093757867591:web:b39bf95cec930914838362',
    messagingSenderId: '1093757867591',
    projectId: 'todotask-fdef8',
    authDomain: 'todotask-fdef8.firebaseapp.com',
    storageBucket: 'todotask-fdef8.appspot.com',
  );
}
